import React from 'react'
import ServHero from '../components/ServHero'
import Header from '../components/Header'
import ServOur from '../components/ServOur'
import Industries from '../components/Industries'
import AndroidServ from '../components/AndroidServ'
import ForDev from '../components/ForDev'
import TabSection from '../components/Tabs'
import Process from '../components/Process'
import WhyChoose from '../components/WhyChoose'
import Keen from '../components/Keen'
import Footer from '../components/Footer'

function Iot() {
  return (
    <>
    <Header/>
    <ServHero title="IoT Development Company" subtitle="Digital Products that are Faster, Smarter & Better" para="IoT is making impossible say out loud- everything is possible. In this fast paced word where every passing second is a treasure, IoT is enhancing business proficiency, Hire the best IoT app development company in India to increase your ROI with a futuristic IoT app." bgurl="/images/iotservbg.jpg" />
      <div className="servour">
        <div className="container">
          <ServOur leftTitle="IoT DEVELOPMENT SERVICES" rightpara="We have the skills, insight, mastery, and ability to smartly unleash the untapped possibilities of your company as one of the most dependable IoT app development companies." />
            <div className="serv-bottom">
                <AndroidServ icon="/images/iot1.png" title="Web Bluetooth Apps Development" para="Without needing to install an app, Web Bluetooth allows you to control any Bluetooth Low Energy device (smart home appliances, health accessories) straight from your smartphone."/>

                <AndroidServ icon="/images/iot2.png" title="Wearable Apps Development" para="Our team of app developers in Dubai has extensive experience developing wearable apps such as smart jewellery, body-mounted sensors, fitness trackers, smart clothes, AI hearing aids, and other similar devices."/>
                
                <AndroidServ icon="/images/iot3.png" title="iBeacon Apps Development" para="Our clients can choose from a variety of off-the-shelf iBeacon solutions. Enhanced In-Store Experience, improved Tracking, and more precise Indoor Location are just a few of the iBeacon uses."/>

                <AndroidServ icon="/images/iot4.png" title="IoT and Blockchain" para="IoT and Blockchain To improve supply chain visibility and quality assurance, our blockchain-powered IoT network offers safe and seamless communication across sensors, distributed ledgers, and databases."/>

                <AndroidServ icon="/images/iot5.png" title="IoT and Machine learning" para="Predictive maintenance, CCTV surveillance, and predictive supply chain benefits from the combination of IoT and machine learning technology."/>

                <AndroidServ icon="/images/iot6.png" title="IoT and Big Data" para="A vast volume of unstructured data generated by IoT devices may be gathered in a big data system and plotted for enhanced visualisation and inference of intriguing results."/>

                <AndroidServ icon="/images/iot7.png" title="IoT Platform Integration" para="Integration of your product across multiple channels with connected devices like point-of-sale systems, sensor gateways, and even social media will give your product a redefined exposure."/>

                <AndroidServ icon="/images/iot8.png" title="IoT Cloud Development" para="Our team provides development services for processing, commanding & analytics cloud services. Prime focus of this service remains intact to secure functionality and facilitate flexibility."/>
            </div>
        </div>
    </div>
    <ForDev devbanner="/images/iotbanner.png" devtitle="IoT Empowering Enterprises" devstrong="" devpara1="Because the Internet now rules the globe, the potential created by IoT are virtually endless.In simple words IoT is connecting physical devices to the interne. This enables simplified data exchange and as a result easier lives. IoT has also enabled full industrialization in a plethora of industries including digital healthcare, remote learning, and linked manufacturing, as well as micro-mobility and sustainability. To safeguard their credential data while transmitting from one device to another, all sorts of businesses have powered themselves with IoT." devpara2="" />

    {/* <WhyChoose whytitle="Industries we fuel with Blockchain Technology" whysubtitle="The Blockchain App Development Services that we offer are crafted to power up your business in a decentralized world. We serve our result-driven blockchain app development services to a wide array of industries with their specific components" whycardimg1="/images/wruby1.png" whycardpara1="Ruby on Rails is a clear, logical, simple, lean code base. As a result, it will save time and provide better solutions." whyimgpara1="Development Speed" whycardimg2="/images/wruby2.png"  whycardpara2="Ruby on Rails is localized, so it is a great idea to build a mobile or web application with this framework." whyimgpara2="Localization" whycardimg3="/images/wruby3.png" whycardpara3="Rubi and Rails make it easy to add validations to your application. Henceforth, it is good to use Ruby and Rails for development." whyimgpara3="Validations" whycardimg4="/images/wruby4.png" whycardpara4="Ruby on Rails is enabled with some security measures. If you decide to use it, you follow a secure development process." whyimgpara4="Security"  whycardimg5="/images/wruby5.png" whycardpara5="The Rubi and Rails framework is known for its standards. It means it is an ideal choice for web development." whyimgpara5="Standards" /> */}

    <Process/>
    <Industries />
    <Keen/>
    <TabSection/>
    <Footer/>
    </>
  )
}

export default Iot
